language: java
jdk:
  - openjdk8


branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


before_deploy:
  - zip -r freelecsan-springboot2-webservice *
  - mkdir -p deploy
  - mv freelecsan-springboot2-webservice.zip deploy/freelecsan-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelecsan-springboot2-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

before_install:
  - chmod +x ./gradlew
#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ksan10102@gmail.com